#!/bin/zsh
# Regenerates the built-in models.dev price snapshot the daemon falls back to
# when it has never fetched (or cannot fetch) https://models.dev/api.json.
#
#   scripts/models-dev-snapshot.sh                # download, then generate
#   scripts/models-dev-snapshot.sh /path/api.json # generate from a local copy
#
# The snapshot keeps the api.json shape (provider → models → id → cost /
# limit) but only the fields `ModelPriceTable` reads, so one parser serves
# the live cache and the built-in copy. Every provider is kept: a model the
# agent's own provider does not list (a reseller-only id) still prices.
set -euo pipefail

repo_root="${0:A:h:h}"
output="${repo_root}/Common/Sources/Core/Pricing/ModelPricingSnapshot.generated.swift"
source_url="https://models.dev/api.json"

if [[ $# -ge 1 ]]; then
  input="$1"
else
  input="$(mktemp -t models-dev-api).json"
  echo "models-dev-snapshot: downloading ${source_url}" >&2
  curl -fsSL "${source_url}" -o "${input}"
fi

python3 - "${input}" "${output}" <<'PY'
import datetime, json, sys

source, output = sys.argv[1], sys.argv[2]
with open(source) as handle:
    api = json.load(handle)

providers = {}
model_count = 0
for provider_id, provider in sorted(api.items()):
    models = {}
    for model_id, model in sorted((provider.get("models") or {}).items()):
        cost = model.get("cost") or {}
        entry = {"cost": {}}
        def rates(source):
            kept = {}
            for key in ("input", "output", "cache_read", "cache_write"):
                value = source.get(key)
                if isinstance(value, (int, float)) and not isinstance(value, bool):
                    kept[key] = value
            return kept
        entry["cost"] = rates(cost)
        if "input" not in entry["cost"] or "output" not in entry["cost"]:
            continue
        # Long-context bands: a request whose context exceeds `tier.size` is
        # billed entirely at that band's rates.
        tiers = []
        for tier in cost.get("tiers") or []:
            bound = tier.get("tier") or {}
            size = bound.get("size")
            if bound.get("type", "context") != "context" or not isinstance(size, int) or isinstance(size, bool):
                continue
            tiers.append({"tier": {"type": "context", "size": size}, **rates(tier)})
        if tiers:
            entry["cost"]["tiers"] = tiers
        elif isinstance(cost.get("context_over_200k"), dict):
            entry["cost"]["context_over_200k"] = rates(cost["context_over_200k"])
        context = (model.get("limit") or {}).get("context")
        if isinstance(context, int) and not isinstance(context, bool):
            entry["limit"] = {"context": context}
        models[model_id] = entry
        model_count += 1
    if models:
        providers[provider_id] = {"models": models}

lines = ["{"]
last = len(providers) - 1
for index, (provider_id, provider) in enumerate(providers.items()):
    line = json.dumps(provider_id) + ":" + json.dumps(provider, separators=(",", ":"), sort_keys=True)
    lines.append(line + ("," if index < last else ""))
lines.append("}")
body = "\n".join(lines)
if '"#' in body:
    raise SystemExit("snapshot contains a raw-string terminator; widen the delimiter")

generated = datetime.date.today().isoformat()
with open(output, "w") as handle:
    handle.write(
        "// Generated by scripts/models-dev-snapshot.sh from https://models.dev/api.json.\n"
        "// Do not edit: rerun the script to refresh. Same shape as api.json, cost and\n"
        "// context only, every provider kept.\n"
        "\n"
        "public enum ModelPricingSnapshot {\n"
        f"    public static let generatedOn = \"{generated}\"\n"
        f"    public static let providerCount = {len(providers)}\n"
        f"    public static let modelCount = {model_count}\n"
        "    public static let json: String = #\"\"\"\n"
        f"{body}\n"
        "\"\"\"#\n"
        "}\n"
    )
print(f"models-dev-snapshot: {len(providers)} providers, {model_count} models → {output}", file=sys.stderr)
PY
